-- MySQL Script generated by MySQL Workbench
-- Thu Aug 27 20:04:07 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA  mydb   ;

-- -----------------------------------------------------
-- Table mydb.orders
-- -----------------------------------------------------
CREATE TABLE  mydb.orders (
  id INT NOT NULL ,
  object_id INT NULL,
  object_type VARCHAR(45) NULL,
  price FLOAT NULL,
  status INT NULL,
  user_id INT NULL,
  create_time TIMESTAMP NULL,
  PRIMARY KEY (id));


-- -----------------------------------------------------
-- Table mydb.promo_sites
-- -----------------------------------------------------
CREATE TABLE  mydb.promo_sites (
  id INT NOT NULL,
  object_name VARCHAR(45) NULL,
  object_description LONGTEXT NULL,
  object_coordinate VARCHAR(45) NULL,
  object_address TEXT NULL,
  price VARCHAR(45) NULL,
  metro_ids INT NULL,
  list VARCHAR(45) NULL,
  template_id INT NULL,
  contacts VARCHAR(45) NULL,
  user_id INT NULL,
  published TINYINT NULL,
  PRIMARY KEY (id));


-- -----------------------------------------------------
-- Table mydb.flyers
-- -----------------------------------------------------
CREATE TABLE  mydb.flyers (
  id INT NOT NULL,
  object_name VARCHAR(45) NULL,
  object_description LONGTEXT NULL,
  object_coordinate VARCHAR(45) NULL,
  object_address TEXT NULL,
  price VARCHAR(45) NULL,
  metro_ids INT NULL,
  list VARCHAR(45) NULL,
  template_id INT NULL,
  contacts VARCHAR(45) NULL,
  user_id INT NULL,
  published TINYINT NULL,
  PRIMARY KEY (id),


-- -----------------------------------------------------
-- Table mydb.metro
-- -----------------------------------------------------
CREATE TABLE  mydb.metro (
  id INT NOT NULL ,
  title_ru VARCHAR(50) NULL,
  coordinates VARCHAR(45) NULL,
  PRIMARY KEY (id));


-- -----------------------------------------------------
-- Table mydb.streets
-- -----------------------------------------------------
CREATE TABLE  mydb.streets (
  id INT NOT NULL,
  city_id INT NULL,
  region_id INT NULL,
  title_ru VARCHAR(45) NULL,
  street_type VARCHAR(45) NULL,
  PRIMARY KEY (id));


-- -----------------------------------------------------
-- Table mydb.cities
-- -----------------------------------------------------
CREATE TABLE  mydb.cities (
  id INT NOT NULL ,
  title_ru VARCHAR(70) NULL,
  coordinates VARCHAR(45) NULL,
  PRIMARY KEY (id));


-- -----------------------------------------------------
-- Table mydb.regions
-- -----------------------------------------------------
CREATE TABLE  mydb.regions (
  id INT NOT NULL ,
  title_ru VARCHAR(45) NULL,
  regionscol VARCHAR(45) NULL,
  PRIMARY KEY (id));


DROP SEQUENCE IF EXISTS mydb.orders_id_sequence;
CREATE SEQUENCE  mydb.orders_id_sequence;
DROP SEQUENCE IF EXISTS mydb.metro_id_sequence;
CREATE SEQUENCE  mydb.metro_id_sequence;
DROP SEQUENCE IF EXISTS mydb.cities_id_sequence;
CREATE SEQUENCE  mydb.cities_id_sequence;
DROP SEQUENCE IF EXISTS mydb.regions_id_sequence;
CREATE SEQUENCE  mydb.regions_id_sequence;
